version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: auth-app-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    networks:
      - auth-app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: auth-app-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/auth-app?authSource=admin
      - JWT_SECRET=your-secret-key
      - JWT_REFRESH_SECRET=your-refresh-secret-key
      - JWT_EXPIRATION=15m
      - JWT_REFRESH_EXPIRATION=7d
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - mongodb
    networks:
      - auth-app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: auth-app-client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - server
    networks:
      - auth-app-network

volumes:
  mongodb_data:

networks:
  auth-app-network:
    driver: bridge
